# Generated by Django 6.0.4 on 2026-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='صورة البانر')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('btn_text_ar', models.CharField(default='اطلب الآن', max_length=50, verbose_name='نص الزر (عربي)')),
                ('btn_url', models.CharField(default='/', max_length=255, verbose_name='رابط الزر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل؟')),
            ],
            options={
                'verbose_name': 'بانر الصفحة الرئيسية',
                'verbose_name_plural': 'بانرات الصفحة الرئيسية (السلايدر)',
                'ordering': ['order'],
            },
        ),
    ]
