# Generated by Django 6.0.4 on 2026-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='أسود', max_length=50, verbose_name='اللون'),
        ),
    ]
