# Generated by Django 6.0.4 on 2026-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(default='#111111', max_length=20, verbose_name='كود اللون (Hex)'),
        ),
    ]
