# Generated by Django 6.0.4 on 2026-05-04 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order_alter_orderitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('region', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('address', models.CharField(max_length=500, verbose_name='العنوان التفصيلي')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='عمارة')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='دور')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='شقة')),
                ('landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name='علامة مميزة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
