# Generated by Django 6.0.4 on 2026-05-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='action_hint_ar',
            field=models.CharField(blank=True, default='لطلب مُهاجر الآن', max_length=100, null=True, verbose_name='الجملة التحفيزية فوق الزر (عربي)'),
        ),
    ]
