# Generated by Django 6.0.4 on 2026-05-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_heroslide_action_hint_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_ar',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_en',
        ),
        migrations.AddField(
            model_name='product',
            name='color_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون (عربي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(default='#111111', max_length=20, verbose_name='كود اللون (Hex)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون (إنجليزي)'),
        ),
    ]
