# Generated by Django 6.0.4 on 2026-05-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_productvariant_color_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_code',
        ),
    ]
