# Generated by Django 6.0.4 on 2026-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_productvariant_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='تكلفة الشحن')),
            ],
            options={
                'verbose_name': 'إعداد المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
