# Generated by Django 6.0.4 on 2026-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_storesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الطلب'),
        ),
    ]
