# Generated by Django 6.0.4 on 2026-05-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
