# Generated by Django 6.0.4 on 2026-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_status_536f03_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_user_id_1fd99b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_trackin_67ff52_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_is_acti_19c4fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_categor_591340_idx',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية في المخزن'),
        ),
    ]
