# Generated by Django 5.0.4 on 2026-05-27 16:41

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'مشرف (Staff)',
                'verbose_name_plural': 'المشرفين (Staff)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', accounts.models.CustomUser.objects),
            ],
        ),
    ]
