# Generated by Django 5.0.6 on 2026-05-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_productprint_productimage_product_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_print',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productprint', verbose_name='الطبعه'),
        ),
    ]
