# Generated by Django 5.0.6 on 2026-06-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_print',
        ),
    ]
