# Generated by Django 5.0.6 on 2026-06-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_product_print'),
        ('products', '0010_remove_productimage_product_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcolor', verbose_name='اللون'),
        ),
    ]
