# Generated by Django 5.0.6 on 2026-06-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_product_color'),
        ('products', '0012_globalcolor_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.masterstockvariant', verbose_name='المتغير (مقاس/لون)'),
        ),
    ]
