# Generated by Django 5.0.6 on 2026-05-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_weight_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطبعه')),
                ('icon', models.ImageField(help_text='صورة مصغرة تظهر كزر', upload_to='products/prints/icons/', verbose_name='صورة الزر (أيقونة)')),
                ('main_image', models.ImageField(upload_to='products/prints/main/', verbose_name='الصورة الرئيسية للطبعه')),
                ('is_default', models.BooleanField(default=False, verbose_name='طبعه افتراضية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Print',
                'verbose_name_plural': 'Product Prints',
                'db_table': 'store_productprint',
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_print',
            field=models.ForeignKey(blank=True, help_text='لو الصورة دي تابعة لطبعه معينة، اختارها من هنا.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.productprint', verbose_name='الطبعه (اختياري)'),
        ),
    ]
