# Generated by Django 5.0.6 on 2026-05-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productprint_productimage_product_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_print',
            field=models.ForeignKey(blank=True, help_text='لو المقاس ده لطبعه معينة، اختارها من هنا.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productprint', verbose_name='الطبعه (اختياري)'),
        ),
    ]
