# Generated by Django 5.0.6 on 2026-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_product_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprint',
            name='icon',
        ),
    ]
