# Generated by Django 5.0.6 on 2026-05-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productprint_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_print',
        ),
    ]
