# Generated by Django 5.0.6 on 2026-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productvariant_product_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprint',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إذا تم تحديده، سيتم استخدام هذا السعر بدلاً من السعر الأساسي للمنتج.', max_digits=10, null=True, verbose_name='سعر الطبعه'),
        ),
    ]
