# Generated by Django 5.0.6 on 2026-06-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_product_print'),
        ('orders', '0003_remove_orderitem_product_print'),
        ('products', '0009_productprint_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_print',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_en',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم اللون (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم اللون (إنجليزي)')),
                ('color_code', models.CharField(default='#111111', max_length=20, verbose_name='كود اللون (Hex)')),
                ('main_image', models.ImageField(upload_to='products/colors/main/', verbose_name='الصورة الرئيسية للون')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='إذا تم تحديده، سيتم استخدام هذا السعر بدلاً من السعر الأساسي للمنتج.', max_digits=10, null=True, verbose_name='سعر اللون')),
                ('is_default', models.BooleanField(default=False, verbose_name='لون افتراضي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'db_table': 'store_productcolor',
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(blank=True, help_text='لو الصورة دي تابعة للون معين، اختارها من هنا.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.productcolor', verbose_name='اللون (اختياري)'),
        ),
        migrations.DeleteModel(
            name='ProductPrint',
        ),
    ]
