# Generated by Django 5.0.6 on 2026-06-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_product_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, help_text='حدد اللون الذي ينتمي إليه هذا المقاس والمخزون. اتركها فارغة إذا كان ينطبق على كل الألوان.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productcolor', verbose_name='اللون (اختياري)'),
        ),
    ]
