# Generated by Django 5.0.6 on 2026-06-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم اللون (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم اللون (إنجليزي)')),
                ('color_code', models.CharField(default='#111111', max_length=20, verbose_name='كود اللون (Hex)')),
            ],
            options={
                'verbose_name': 'لون أساسي سادة',
                'verbose_name_plural': 'الألوان الأساسية السادة',
                'db_table': 'store_globalcolor',
            },
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='اسم اللون للطبعة (عربي)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم اللون للطبعة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='global_color',
            field=models.ForeignKey(help_text='سيتم سحب مقاسات ومخزون هذا المنتج من مخزون اللون الأساسي المختار هنا.', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.globalcolor', verbose_name='اللون الأساسي السادة (المرجع)'),
        ),
        migrations.CreateModel(
            name='MasterStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='القسم (نوع المنتج)')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.globalcolor', verbose_name='اللون الأساسي السادة')),
            ],
            options={
                'verbose_name': 'مخزون أساسي',
                'verbose_name_plural': 'المخزون الأساسي (Master Stock)',
                'db_table': 'store_masterstock',
            },
        ),
        migrations.CreateModel(
            name='MasterStockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='المقاس')),
                ('weight_range', models.CharField(blank=True, help_text='مثال: 70-85', max_length=50, null=True, verbose_name='الوزن (من-إلى)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='المخزون')),
                ('master_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.masterstock')),
            ],
            options={
                'verbose_name': 'مقاس مخزون',
                'verbose_name_plural': 'مقاسات المخزون',
                'db_table': 'store_masterstockvariant',
                'ordering': ['id'],
            },
        ),
    ]
