# Generated by Django 5.0.6 on 2026-06-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_variant'),
        ('orders', '0005_alter_orderitem_variant'),
        ('products', '0012_globalcolor_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.AlterUniqueTogether(
            name='masterstock',
            unique_together={('category', 'color')},
        ),
    ]
